POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2NjhkNGRmNmYyY2I2MGUzODI4YzM3OTYiLCJpYXQiOjE3MjA1Mzg2NjcsImV4cCI6MTcyMDU0MjI2N30.0QLW0Ze3OHP9wW-AtaArv1terOUuwQGafEBQPuZD5-4

{
   "title": "Middlemare",
   "author": "Artturi Kerminen",
   "url": ""
}
